Clang v7 is required for flecstan
/home/flecsi/flecsi/tools/flecstan/src/flecstan-visitor.cc:186:53: error: 'const class clang::VarDecl' has no member named 'getBeginLoc'; did you mean 'getDefinition'?
    const MacroCall *const iptr = prep.findcall(var->getBeginLoc());
                                                     ^~~~~~~~~~~
                                                     getDefinition